title: Bach Huy Pham # your name (or website title) here
logo: "/images/profile_pic_2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspired data analyst pivoting my career through self-directed learning and hands-on personal projects.
  <br><br>
  Passionate about solving business problems with insights gained from data analytics.
  <br><br>
  <a href="https://www.linkedin.com/in/bachpham/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
